name: ${name}
version: ${version}
main: ${mainClass}
author: ${author}
website: ${url}
softdepend: [WorldEdit]

commands:
    pumpkincarving:
        description: Utility command for the PumpkinCarving plugin
        aliases: [pcarv, pcarving]
        permission: pumpkincarving.admin

permissions:
    pumpkincarving.admin:
        description: Required to view plugin version information and reload config
        default: op